name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 
    - name: Set up JDK 11
      uses: actions/setup-java@v3  
      with:
        java-version: '11'
        distribution: 'temurin'  # Temurin - это новое имя для AdoptOpenJDK
    - name: Compile and Test
      run: |
        javac NumberAnalyzer.java
        javac -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar NumberAnalyzerTest.java
        java -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore NumberAnalyzerTest
