name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Позволяет запускать workflow вручную из GitHub UI.

jobs:
  build:
    runs-on: ubuntu-latest  # Определяет, что задача будет выполняться на последней версии Ubuntu

    steps:
    - uses: actions/checkout@v2  # Позволяет получить копию вашего репозитория на runner

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Устанавливает JDK версии 11
        distribution: 'adopt'  # Использует AdoptOpenJDK

    - name: Build and Test
      run: |
        javac NumberAnalyzer.java
        javac -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar NumberAnalyzerTest.java
        java -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore NumberAnalyzerTest
